### ISSUE TITLE
How did you determine hat hashtags to use?

### ISSUE THREAD

**Issue by SalehAhmad1** [alexdrk14/RussoUkrainianWar_Dataset#1]
Hello. Great work, indeed. I have a question. How did you determine, which hashtags to go for to get data relavant to war?
I would appreciate a quick response. Thanks.

**Comment by alexdrk14** [comment]
Hi @SalehAhmad1, we are manage to select popular hashtags at the first days of conflict. As you know twitter provide popular hashtags by country, so we manage to select Russia, Ukraine and some European countries in order to collect most popular hashtags. Furthermore, we manually inspect tweets where these hashtags was used, in order to identify the relevance of the content. At the end we kept hashtags that was used as relevant to discussion topic.

**Comment by SalehAhmad1** [comment]
Do you have a source code for the scraping that you can give me?

**Comment by SalehAhmad1** [comment]
And which libraries did you use for this?

**Comment by alexdrk14** [comment]
You can use Twitter API which is available based on subscription : https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api

Or in other case you can use hydrator: https://github.com/DocNow/hydrator , but due the last updates of Twitter / X i don't know if this options is already blocked.

In our case we manage to collect this dataset via Twitter API, with use python3 library of tweepy https://www.tweepy.org/ .

**Comment by SalehAhmad1** [comment]
What did you use?

**Comment by alexdrk14** [comment]
As i mentioned above, we used Twitter API since we have free  Research subscription plan. Currently there is no free subscriptions even for the researchers, so we stoped our collection.
